### ISSUE TITLE
Add links to request access page

### ISSUE THREAD

**Issue by dometto** [UtrechtUniversity/vre-docs#56]
#52 adds basic information on how to request access. However, a neater way suggested by @jelletreep could be to add a direct link to the catalog item page in the portal where access can be requested.

This is a bit more complicated, since in the workspace catalog we show e.g. 'Python Workbench', but in fact there are various Catalog Items (Python Workbench Desktop, Python Workbench CLI), etc.

One approach could be to add more metadata to each workspace type. For instance, for `python-workbench.qmd`:

```yaml
flavours:
  - name: Python Workbench Desktop
    description: "Bla"
    id: surf-catalog-item-id
```

...and then create a table with names, descriptions, and links to each flavour in the markdown file.

Does that sound good, or would it unnecessarily complicate things?
